### ISSUE TITLE
Should we support a custom shapes type? i.e. NovelRT::Graphics::CustomShape or something similar?

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#128]
Title.

The thought process here being that we could unify a lot of our logic in places such as `BasicFillRect` and `ImageRect` in a way that allows for us to also expose the base as a type in the end-user LLAPI itself, whereby they could provide their own `std::vector<Maths::GeoVector<float>>` of points for their own polygons.

This is something I just was thinking about on the train ride home, lol. What do you guys reckon?

**Comment by tannergooding** [comment]
I think from the perspective of the llapi, we could have the `render object` which carries the vertex/index buffer (maybe split into `RenderObject` and `IndexedRenderObject : RenderObject`?) and the associated shader state.

From that, you can have specializations (like `Rect : RenderObject`, `ColoredRect : Rect` or `TexturedRect : Rect`) which can know what parameters to pass into the shader pipeline associated with the object.

**Comment by tannergooding** [comment]
Once you get into DX12 and Vulkan, that is roughly how things are split up. You have the pipeline and inputs to that pipeline (which is generally the vertex/index buffer at a minimum; but often includes textures or the camera state, etc).

The buffers describe the vertices and the indices used to create the triangles.
The pipeline defines the various shader stages enabled, their inputs/outputs, and the shader bytecode to be executed for each.

So, when you render an object you would set the pipeline state, then the buffers, and then draw the instanced object.
Keeping in mind that state changes have some cost and too many can be bad, so you might want to render a set of objects that share the same pipeline, for example, rather than setting it for each draw. (see also: https://github.com/KhronosGroup/Vulkan-Guide/blob/18276f29232d8b03c93b7730c28b543d81e11a58/chapters/common_pitfalls.md#multiple-pipelines)

**Comment by RubyNova** [comment]
This type is no longer required due to the ECS-driven model the engine now follows. Closing.
