### ISSUE TITLE
Mount CoreCLR for bi-directional bindings.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#14]
This ticket specifically lays out what is required for the .NET and Ink bindings.

We need to be able to essentially mount/host CoreCLR ourselves from inside the engine Unity style. There has been multiple discussions on why we wish to take this approach over just using extern C like we are for Rust and JS and then just P/Invoking in is because this will actively sacrifice universal Ink support. One of the main goals of this engine is to provide Ink to all of the language APIs universally. To see more about Ink, you can view it here: https://github.com/inkle/ink

The other main reason for hosting the CLR ourselves is because we can have communication both ways - as in, the engine core invokes C# code which can then come back into the engine core, much like how Unity approaches it.

The downside to this is, naturally, it will to be more work to implement, test, etc. This will probably require extensive tests once we have set up the google test suite (this is still on our TODO).

The other concern is without this, we can't actually make an alpha build of any kind as we planned to have C# and possibly Ink from the get-go in terms of the roadmap.

If there is a faster way to achieve this, you are welcome to suggest it here, however this is probably the best approach to my understanding.

[AB#6](https://dev.azure.com/NovelRT/16e5528b-8bb4-4e2b-b064-e26926458e42/_workitems/edit/6)

**Comment by tannergooding** [comment]
Going to leave this as a reference as it will be the starting point for almost any work done here: <https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting>

**Comment by tannergooding** [comment]
Overall, the approach/setup will be fairly similar to P/Invoke.

The primary difference is that instead of declaring extern functions and annotating them with `DllImport`, you will instead be declaring delegates and annotating them with `UnmanagedFunctionPointer`. You will then rely on the `Marshal.GetDelegateForFunctionPointer` API to convert C++ function pointers to something that can be invoked by C# and `Marshal.GetFunctionPointerForDelegate` to convert C# methods into something that can be invoked by C++.

**Comment by RubyNova** [comment]
Would we need to point to extern C methods for that or can we just directly use the C++ API that's being worked on?

**Comment by tannergooding** [comment]
You can point to any method that you want. The hard part is defining a mechanism for lookup of the relevant signatures, etc.

On the native side, the hosting APIs basically define the basis for loading up a CoreCLR instance. You are then able to resolve methods using the fully qualified name (similar to reflection) in order to get an invocable function pointer.

The first function that you invoke here should likely be a singular entry point that goes and sets up all the managed state (in C# code) and takes in a corresponding native signature for where the reverse lookup could happen.

You might effectively have (in psuedo-code and simplified) something like:

```cs
public class ManagedHost    // Managed Side
{
    private NativeLookupMethod _nativeLookup;

    public static void EntryPoint(NativeLookupMethod nativeLookup);

    [UnmanagedFunctionPointer]
    public delegate IntPtr NativeLookupMethod(args);
}

class NativeHost    // Native Side
{
    public: static void* LookupMethod(args);
}
```

The `NativeHost::LookupMethod` is what is passed into the entry point and is what allows for the bi-directional communication.

You would then need to decide how everything flows between the two of them. For the managed side, its a bit easier because theoretically everything is accessible via the fully qualified name and the metadata existing at runtime.

For the native side, it is a bit harder because the RTTI (Run Time Type Information) is generally fairly limited in nature, so I imagine you will need a bit more logic to translate the input args into the relevant native signature you want.

**Comment by tannergooding** [comment]
But, once you have a mechanism to do lookup both ways; you can define your actual APIs however you want and just route the few communication APIs through those functions lookup functions.

The pseudo-code, for a full example, might look something like:
```cs
int c_main(int count, char** argv)
{
    // bit more complicated that this, but its basically just this
    hostfxr_initialize_for_runtime_config();
    get_runtime_delegate = hostfxr_get_runtime_delegate();

    get_runtime_delegate(context, hdt_load_assembly_and_get_function_pointer, &load_assembly_and_get_function_pointer);
    load_assembly_and_get_function_pointer("path/to/NovelRT.Managed.dll", "AssemblyQualifiedTypeName", "MethodName", "AssemblyQualifiedTypeName_OfDelegateSignatureForMethodName", nullptr, &ManagedEntryPoint);

    ManagedEntryPoint(&NativeHost::LookupMethod);

    // main loop
}

struct MyStruct
{
    private: float m_value;

    public: MyStruct(float value)
        : m_value(value)
    {
    }

    public: float GetValue()
    {
        return m_value;
    }

    public: static MyStruct Create(float value)
    {
        return MyStruct(value);
    }
};

enum class NativeMethodId
{
    MyStruct_Create,
    MyStruct_GetValue
}

class NativeHost
{
    public: static void* LookupMethod(NativeMethodId id)
    {
        switch (id)
        {
            case NativeMethodId::MyStruct_ctor:
            {
                return (void*)&MyStruct::Create;
            }

            case NativeMethodId::MyStruct_GetValue:
            {
                return (void*)&MyStruct::GetValue;
            }
        }
    }
};
```

and then:
```
namespace NovelRT
{
    public static class ManagedHost
    {
        private static NativeLookup _nativeLookup;

        public static NativeLookupSignature NativeLookup => _nativeLookup;

        public static void EntryPoint(NativeLookupSignature nativeLookup)
        {
            _nativeLookup = nativeLookup;
            MyStruct.Initialize();

            var myStruct = MyStruct.Create(MathF.PI);
            Console.WriteLine(myStruct.Value);
        }

        [UnmanagedFunctionPointer]
        public delegate void EntryPointSignature(NativeLookupSignature nativeLookup);

        [UnmanagedFunctionPointer]
        public delegate IntPtr NativeLookupSignature(NativeMethodId id);
    }

    public unsafe struct MyStruct
    {
        private static CreateSignature _nativeCreate;
        private static GetValueSignature _nativeGetValue;

        public static void Initialize()
        {
            _nativeCreate = Marshal.GetDelegateForFunctionPointer<CreateSignature>(ManagedHost.NativeLookup(NativeMethodId.MyStruct_Create));
            _nativeGetValue = Marshal.GetDelegateForFunctionPointer<GetValueSignature>(ManagedHost.NativeLookup(NativeMethodId.MyStruct_GetValue));
        }

        public static MyStruct Create() => _nativeCreate();

        private float m_value;

        public float Value => _nativeGetValue(&this);

        [UnmanagedFunctionPointer]
        public delegate MyStruct CreateSignature(float value);

        [UnmanagedFunctionPointer]
        public delegate float GetValueSignature(MyStruct* pThis);
    }

    public enum NativeMethodId
    {
        MyStruct_Create,
        MyStruct_GetValue
    }
}
```

Naturally the real code would likely be more complicated than a struct with a getter, but it shows the general premise behind this.

For virtual methods, you can actually avoid needing to do something like "Initialize". This is because the function pointers are resolvable from the VTBL which is just another field of the struct/class. However, you need to deal with cross platform VTBL layout differences at that point (which is doable, just more work and "potentially" less portable).

**Comment by RubyNova** [comment]
We are no longer hosting CoreCLR. Closing.
