### ISSUE TITLE
Modifying GeoVector to support GLM.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#20]
I'm unsure if this is even beneficial for us at this point but I've recently discovered GLM exists.

GLM is the official OpenGL maths library

Any thoughts on whether we should refactor to use it? Its probably faster than our own implementation but it may hurt our support for DX and Vulkan in the future.

**Comment by tannergooding** [comment]
It might be beneficial to have `GeoVector` wrap it for certain functionality. Then it is easily swappable without taking a direct dependency (in the public surface area).

**Comment by capnkenny** [comment]
I think Tanner's idea would be good here. That, and GLM wouldn't hinder a Vulkan implementation as Vulkan has no linear algebra operations (glm is actually recommended in this case), but it'd be useless for a DX implementation if i recall correctly.

**Comment by RubyNova** [comment]
Ok, so then the question is, how much of a priority is it? Things are working as of PR #23 so I'd argue this isn't an immediate essential as we have other concerns such as text to implement.

**Comment by capnkenny** [comment]
This should be lower priority IMO. If we can get the basic implementation done without needing to wrap GeoVector or modify it much, then we should be okay to push it back. 

However, if there comes time where you will need to start adding a lot more to GeoVector and glm would assist with this, then we'd revisit. (This part I admit I'm unsure of since I'm not as familiar with gfx programming)

**Comment by RubyNova** [comment]
Due to this being now required it has already been added to the codebase in #26 . Closing.
