### ISSUE TITLE
CI: investigate moving to Github Actions.

### ISSUE THREAD

**Issue by Tylertron1998** [novelrt/NovelRT#218]
Github Actions is a CI/CD pipeline that is scriptable with an API, and has a neat feature called [problem matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md) - which is super great for developer experience. We could also consider using it to push release builds of the engine, ready to be used by consumers.

**Comment by capnkenny** [comment]
I am aware of GH Actions being able to support our pipeline, so this wouldn't be so bad - especially since it would no longer require AzDO access so we could keep everything here. With that said, a few concerns:
1) (Not that AzDO has this too but) Is there support on Actions to have a UK English linter? (This was an ask by @RubyNova since we're working on a UK codebase.)

2) How do we proceed to log historical test results? As of now, it looks like we are able to log the test results from our unit tests into AzDO Test Plans, however I don't believe GH has an alternative to this.

**Comment by Tylertron1998** [comment]
Actions is completely scriptable - so it's more a question of 'does a UK English linter exist?'; if so definitely.

Actions do save output from any workflow based on commit hash - however, they [have a time limit and do expire after 90 days.](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete). 

IMO this isn't a massive issue, I am not sure why we'd need to look into test logs from 90+ days ago -- and the code is still there so we can rerun tests manually if that's the case.

**Comment by RubyNova** [comment]
We found a very...erm....**patriotic** linter shall we say? for US english, so we might just be able to fork that and rework it for UK english.

**Comment by Tylertron1998** [comment]
awesome! If you can drop it to me either here, or in discord, I'll be happy to pull up a fork of novelrt and give it a test run!

**Comment by Tylertron1998** [comment]
I've found this: https://github.com/nuspell/nuspell which seems to be our best option. It supports Hunspell libraries (yay for UK English!) but doesn't differentiate between source and non source files. I'll play about and see if I can make it only operate over files we care about (i.e. source & cmake files), ignore any language keywords, and go from there.

**Comment by capnkenny** [comment]
> IMO this isn't a massive issue, I am not sure why we'd need to look into test logs from 90+ days ago -- and the code is still there so we can rerun tests manually if that's the case.

It isn't that we'd need test logs from 90 days ago, this is more or less to see if/when our unit tests start to fail erratically, we can see what changed over time on an easy to see dashboard. This is really just for our daily builds nonetheless, and not the PR pushes - I don't think there's need to warrant one for each push per PR.

On that note, maybe it's something that we can wait on anyways since our AzDO activity has not been frequent enough..

**Comment by capnkenny** [comment]
Hey @Tylertron1998 - did you still want to look into this? Or is this open for anyone to pick up?

**Comment by Tylertron1998** [comment]
Absolutely - in terms of a 'linter' for UK English, this doesn't seem too possible right now without delving into the innards or lord Clang (other compiler options are available, terms and conditions apply, remove the wrapper before microwaving) - I'll make a fork of latest master and see what I can do :D

**Comment by capnkenny** [comment]
Resolved by #237
