### ISSUE TITLE
Default CMake behaviour causes NovelRT to attempt to build when it could not find conan_paths.cmake.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#325]
In the default behaviour, we should probably fail fast if this file cannot be found, as we assume conan is there by default.

**Comment by capnkenny** [comment]
Correct me if I'm wrong here, but this sounds like a potential bug with CMake and not on our end.

Currently we have the project-level CMakeLists.txt call to include the `conan_paths.cmake` file as a _required_ include, so an error should be raised and configuration should subsequently fail. It's been this way since prior to 3.13, which is our minimum.

@FiniteReality - your thoughts?

**Comment by RubyNova** [comment]
It does raise an error. It just carries on because its not logged as fatal.

**Comment by capnkenny** [comment]
Yeah, that' sounds specific to the version that was used then, because this should occur once `include` cannot find the file:
`Configuring incomplete, errors occurred!`

Based on the issue a user was having on Discord, this is what occurred:

`
PS C:\Users\[CENSORED]\Desktop\NovelRT> cmake .
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
CMake Error at CMakeLists.txt:53 (include):
  include could not find requested file:

    C:/Users/[CENSORED]/Desktop/NovelRT/conan_paths.cmake


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE dot) (Required is at least version "1.8.17")
Doxygen 1.8.17 was not found, building documentation is disabled.
  Determining projects to restore...
  All projects are up-to-date for restore.
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) (Required
  is at least version "1.0.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindBZip2.cmake:66 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/NovelRT/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/[CENSORED]/Desktop/NovelRT/CMakeFiles/CMakeOutput.log".`

Are you saying that you just want to fail fast instead at the include? Since this looks like it'll still report that configuration failed and something needs changing (maybe I'm being dense hahaha 🙂 )

**Comment by FiniteReality** [comment]
I don't *think* failing fast is "The CMake way" - I've read a few threads on the CMake forums that seem to suggest that continuing is intentional, and the only movement in this has been within the last few months: https://gitlab.kitware.com/cmake/cmake/-/issues/1935

However, a potential workaround would be to do something like this:
```cmake
macro(angry_include file)
    include("${file}" OPTIONAL RESULT_VARIABLE file_found)
    if (NOT file_found)
        message(FATAL_ERROR "Could not include file ${file}")
    endif()
    unset(file_found
endmacro()
```

**Comment by RubyNova** [comment]
The URL returns 404.

**Comment by FiniteReality** [comment]
Huh. I swear it was working earlier.
